africanawiki_geodata/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import api
from rest_framework.authtoken import views
from engine.views import home
from engine.views import public_datasets
from engine.views import dashboard
from engine.views import request_an_invite
from engine.views import geo_minority_businesses
from engine.views import InvitationRequestCreateView
from engine.views import InvitationRequestDetailView
from engine.views import DatasetCreateView
from engine.views import InviteUserView
from engine.views import AcceptInviteView
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.conf import settings

ns_invitations = patterns('',
    url(r'^accept-invite/(?P<key>\w+)/?$',AcceptInviteView.as_view(),name='accept-invite')
)

urlpatterns = patterns('',
    # Examples:
    url(r'^$', home, name='home'),
    url(r'^public_datasets/$', public_datasets, name='public_datasets'),
    url(r'^dashboard/$', login_required(dashboard), name='dashboard'),
    url(r'^geo/minority_businesses/',geo_minority_businesses,name='geo_minority_businesses'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^api/', include('api.urls'), name='api'),

    url(r'^request_an_invite/', InvitationRequestCreateView.as_view(), name='request_an_invite'),
    url(r'^request/(?P<pk>\d+)/(?P<slug>[-\w]+)/$',InvitationRequestDetailView.as_view(),name='invitation_request_detail'),

    url(r'^invite_user/', login_required(InviteUserView.as_view()), name='invite_user'),

    url(r'^dataset/create/', staff_member_required(DatasetCreateView.as_view()), name='dataset_create'),

    url(r'^captcha/', include('captcha.urls')),

    url(r'^api-token-auth/', views.obtain_auth_token),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^invitations/', include(ns_invitations, namespace="invitations")),
)

if settings.DEBUG:
        urlpatterns += patterns('',
            url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                'document_root': settings.MEDIA_ROOT,
            }),
            url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
                'document_root': settings.STATIC_ROOT,
            }),
    )

api/urls.py
from django.conf.urls import url, include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from .views import get_businesses
from engine.models import SBABusiness
from .serializers import BusinessSerializer
from rest_framework.decorators import api_view,permission_classes
from rest_framework.permissions import IsAuthenticatedOrReadOnly,IsAuthenticated

@permission_classes([IsAuthenticatedOrReadOnly])
class BusinessViewSet(viewsets.ModelViewSet):
    queryset = SBABusiness.objects.all()
    serializer_class = BusinessSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'businesses',BusinessViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^get_businesses', get_businesses,name="get_businesses")
]

engine/models.py
from django.conf import settings
from django.db import models
from geoposition.fields import GeopositionField
import geocoder
from omgeo import Geocoder
import geopy
from django.db.models import Lookup
from django.db.models.fields import Field
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse

class SBABusiness(models.Model):
	name_and_trade_name_of_firm = models.CharField(max_length=255,blank=True,null=True)
	contact = models.CharField(max_length=255,blank=True,null=True)
	address = models.CharField(max_length=255,blank=True,null=True)
	capabilities_narrative = models.TextField(blank=True,null=True)
	geoposition = GeopositionField(blank=True,null=True)
	cage_code = models.CharField(max_length=255,blank=True,null=True)
	congressional_district = models.CharField(max_length=255,blank=True,null=True)
	county_code = models.IntegerField(blank=True,null=True)
	duns_number = models.CharField(max_length=20,blank=True,null=True)
	email_address = models.EmailField(blank=True,null=True)
	email_page_url = models.CharField(max_length=255,blank=True,null=True)
	fax_number = models.CharField(max_length=20,blank=True,null=True)
	fiscal_year = models.CharField(max_length=20,blank=True,null=True)
	in_sam = models.CharField(max_length=255,blank=True,null=True) #change to boolean field at some point
	in_tech_net = models.CharField(max_length=255,blank=True,null=True) #change to boolean field at some point
	incorporation_country = models.CharField(max_length=255,blank=True,null=True)
	incorporation_state = models.CharField(max_length=255,blank=True,null=True)
	last_updated = models.CharField(max_length=255,blank=True,null=True)
	main_or_branch = models.CharField(max_length=255,blank=True,null=True)
	metro_stat_area = models.CharField(max_length=255,blank=True,null=True)
	phone_number = models.CharField(max_length=255,blank=True,null=True)
	www_page_url = models.CharField(max_length=255,blank=True,null=True)
	year_established = models.CharField(max_length=255,blank=True,null=True)
	_8a_case = models.CharField(max_length=255,blank=True,null=True)
	_8a_entrance_date = models.CharField(max_length=255,blank=True,null=True)
	_8a_exit_date = models.CharField(max_length=255,blank=True,null=True)
	hubzone_certification_date = models.CharField(max_length=255,blank=True,null=True)
	hubzone_exit_date = models.CharField(max_length=255,blank=True,null=True)
	legal_structure = models.CharField(max_length=255,blank=True,null=True)
	sdb_entrance_date = models.CharField(max_length=256,blank=True,null=True)
	sdb_exit_date = models.CharField(max_length=256,blank=True,null=True)
	keywords = models.TextField(blank=True,null=True)
	is_exporter = models.CharField(max_length=20,blank=True,null=True) #change to boolean field at some point
	business_type = models.TextField(blank=True,null=True)
	dbe_states = models.TextField(blank=True,null=True)
	export_business_activities = models.TextField(blank=True,null=True)
	ownership_self_certs = models.TextField(blank=True,null=True)

	empty_field = models.CharField(max_length=50,blank=True,null=True)
	hashtag_field = models.CharField(max_length=50,blank=True,null=True)

	def __unicode__(self):
		return unicode(self.name_and_trade_name_of_firm)

	def save(self, *args, **kwargs):
		if not self.geoposition:
			
			#omgeo
			"""
			g = Geocoder()
			result = g.geocode(self.address)
			try:
				self.geoposition = [
					result['candidates'][0].y, #switched for ERSI
					result['candidates'][0].x,
				]
			except IndexError:
				print 'error'
				print result
			"""
			#google
			"""
			g = geocoder.google(self.address)
			self.geoposition = g.latlng
			
			"""
			#bing via geopy
			#g = geopy.geocoders.Bing(
			#	api_key='Ao1fBnmH6itsPp9k4DOf5_3X5DCdVUEVp8SOnVpSwpUAse2sMNzOioQq0fCtlfxb')
			
			#DataBC via geopy
			g = geopy.geocoders.DataBC()
			
			#Yandex via geopy
			#g = geopy.geocoders.Yandex()
			
			result = g.geocode(self.address)
			try:
				self.geoposition = [
					result.latitude,
					result.longitude
				]
			except AttributeError:
				'error'
				print result
			print self.address,self.geoposition

		super(SBABusiness,self).save(*args,**kwargs)

class InvitationRequest(models.Model):
	email = models.EmailField(unique=True)
	desired_username = models.CharField(max_length=20,unique=True)
	full_name = models.CharField(max_length=255)
	facebook_url = models.URLField(blank=True,null=True)
	twitter_url = models.URLField(blank=True,null=True)
	linkedin_url = models.URLField(blank=True,null=True)
	github_url = models.URLField(blank=True,null=True)
	reddit_url = models.URLField(blank=True,null=True)
	timestamped_photo = models.ImageField(upload_to="uploaded_images",blank=True,null=True)
	bio = models.TextField(blank=True,null=True)
	is_user_accepted = models.BooleanField(default=False)
	is_admin_accepted = models.BooleanField(default=False)
	is_declined = models.BooleanField(default=False)
	slug = models.SlugField(blank=True,null=True)

	def __unicode__(self):
		return unicode(self.full_name)

	def save(self, *args, **kwargs):
		if not self.slug:
			#Newly created object, so set slug
			self.slug = slugify(self.full_name)
		super(InvitationRequest,self).save(*args,**kwargs)

	def get_absolute_url(self):
		return reverse("invitation_request_detail", kwargs={'pk':str(self.id),'slug':str(self.slug)})

class Dataset(models.Model):
	name = models.CharField(max_length=255)
	link = models.EmailField()
	description = models.TextField(blank=True,null=True)
	image = models.ImageField(upload_to='uploaded_images',null=True,blank=True)

	def __unicode__(self):
		return unicode(self.name)
"""
@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
	if created:
		Token.objects.create(user=instance)
"""

engine/forms.py
from django import forms
from .models import InvitationRequest
from .models import Dataset
from captcha.fields import CaptchaField
from django.utils.translation import ugettext_lazy as _
from allauth.account.adapter import get_adapter
from invitations.models import Invitation
from invitations.forms import CleanEmailMixin

class InvitationRequestForm(forms.ModelForm):
	captcha = CaptchaField()
	class Meta:
		model = InvitationRequest
		exclude = ('is_admin_accepted','is_user_accepted','slug','is_declined')

class DatasetForm(forms.ModelForm):
	class Meta:
		model = Dataset
		exclude = ()

class CustomInviteForm(forms.ModelForm, CleanEmailMixin):
	captcha = CaptchaField()
	email = forms.EmailField(
		label=_("E-mail"),
		required=True,
		widget=forms.TextInput(attrs={"type": "email", "size": "30"}))
	class Meta:
		model = Invitation
		exclude = ('accepted','created','sent','key')

	def save(self, email):
		return Invitation.create(email=email)

engine/views.py
from django.shortcuts import render
from django.conf import settings
from .models import InvitationRequest
from .models import Dataset
from .forms import InvitationRequestForm
from .forms import DatasetForm
from .forms import CustomInviteForm
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import CreateView
from django.views.generic.edit import DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404, HttpResponseRedirect
from invitations.models import Invitation
from django.views.generic import FormView, View
from django.views.generic.detail import SingleObjectMixin
from invitations.app_settings import app_settings
from invitations.forms import InviteForm
from allauth.account.adapter import get_adapter
from invitations import signals
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.models import User

def home(request):
	context = {}
	print settings.DEBUG
	return render(request,
				  'home.html',
				  context)

def public_datasets(request):
	context = {}
	return render(request,
				  'public_datasets.html',
				  context)

def dashboard(request):
	context = {}
	requests = [u for u in InvitationRequest.objects.all() if not User.objects.filter(email=u.email)]

	context['requests'] = requests
	return render(request,
				  'engine/dashboard.html',
				  context)

def geo_minority_businesses(request):
	context = {}
	return render(request,
				  'geohome.html',
				  context)

def request_an_invite(request):
	context = {}
	return render(request,
				  'request_an_invite.html',
				  context)

class InvitationRequestCreateView(SuccessMessageMixin,CreateView):
	model = InvitationRequest
	form_class = InvitationRequestForm
	template_name = 'engine/invitation_request_create.html'
	success_message = "You've successfully requested an invite. We'll get back to you as soon as possible :)"

	def form_valid(self,form):
		self.object = form.save()
		return HttpResponseRedirect(self.get_success_url())

	def form_invalid(self,form):
		return self.render_to_response(
			self.get_context_data(form=form,))

class InvitationRequestDetailView(DetailView):
	model = InvitationRequest
	template_name = 'engine/invitation_request_detail.html'

	def get_success_url(self):
		return reverse("invitation_request_detail", kwargs={
			'pk':str(self.kwargs['pk']),
			'slug':str(self.kwargs['slug'])})

	def get_context_data(self,**kwargs):
		context = super(InvitationRequestDetailView, self).get_context_data(**kwargs)
		return context

class DatasetCreateView(CreateView):
	model = Dataset
	form_class = DatasetForm
	template_name = 'engine/dataset_create.html'

	def form_valid(self,form):
		form = DatasetForm(self.request.POST,self.request.FILES)
		f = form.save(commit=False)
		f.save()
		return super(DatasetCreateView,self).form_valid(form)

class InviteUserView(CreateView):
	model = Invitation
	form_class = CustomInviteForm
	
	template_name = 'engine/invite_user.html'
	def form_valid(self,form):
		email = form.cleaned_data["email"]

		try:
			invite = form.save(email)
			invite.send_invitation(self.request)
		except Exception:
			return self.form_invalid(form)

		return self.render_to_response(
			self.get_context_data(
				success_message='%s has been invited' % email))

	def form_invalid(self, form):
		return self.render_to_response(self.get_context_data(form=form))


class AcceptInviteView(SingleObjectMixin, View):
	form_class = InviteForm
	template_name = 'engine/accept_invite.html'

	def get(self, *args, **kwargs):
		if settings.CONFIRM_INVITE_ON_GET:
			return self.post(*args, **kwargs)
		else:
			raise Http404()

	def post(self, *args, **kwargs):
		self.object = invitation = self.get_object()

		invitation.accepted = True
		invitation.save()
		get_adapter().stash_verified_email(self.request, invitation.email)

		signals.invite_accepted.send(sender=self.__class__,
									 request=self.request,
									 email=invitation.email)

		get_adapter().add_message(self.request,
								  messages.SUCCESS,
								  'invitations/messages/invite_accepted.txt',
								  {'email': invitation.email})

		return redirect(app_settings.SIGNUP_REDIRECT)

	def get_object(self, queryset=None):
		if queryset is None:
			queryset = self.get_queryset()
		print queryset
		try:
			print self.kwargs

			return Invitation.objects.get(key=self.kwargs["key"].lower())
		except Invitation.DoesNotExist:
			raise Http404()

	def get_queryset(self):
		return Invitation.objects.all_valid()

africanawiki_geodata/templates/engine/accept_invite.html
{% extends 'engine/base.html' %}

{% block content %}
<div class="vbvb">
<form action="." method="post">
	{{form.as_p}}
</form>
</div>
{% endblock %}

africanawiki_geodata/templates/engine/business_list.html
{% extends 'engine/engine_base.html' %}
{% block more_css_in_head %}
   
    <script src='https://api.mapbox.com/mapbox.js/v2.2.2/mapbox.js'></script>
    <link href='https://api.mapbox.com/mapbox.js/v2.2.2/mapbox.css' rel='stylesheet' />
    <link rel="stylesheet" type="text/css" href="/static/fonts/fonts.css">
                    <script src="/static/js/jquery-cookie-master/jquery-cookie-master/src/jquery.cookie.js"></script>

{% endblock %}
{% block title_tag %} Browse Leaseful {{data.area}} Listings {% endblock %}

{% block left_sidebar %}

{% endblock %}
{% block content %}
    <div class="dash">
        <div class="content">
            <div class="search">
                <div class="left col-md-7 col-sm-12 col-xs-12 nhp">
                    <form class="controls">
                        <div class="row cf">
                            <div class="lab l col-md-2">Area</div>
                            <div class="inp r col-md-10">
                                <div class="select">
                                    <select id="select" class="bgwhiteimp">
                                        
                                         <option value="University of Arizona" >Arizona (UA) - coming soon</option>
                                    <option value="Florida State University">Florida State (FSU) - coming soon</option>
                                    <option value="University of Georgia">Georgia (UGA) - coming soon</option>
                                    <option value="Georgia Tech">Georgia Tech (GT) - coming soon</option>
                                    <option value="University of Michigan" selected="selected">Michigan (UM)</option>  
                                    <option value="Southern Methodist University" >Southern Methodist (SMU) - coming soon</option>
                                    <option value="Texas Christian University">Texas Christian (TCU) - coming soon </option>
                                    <!--
                                    <option value="Georgetown University ">Georgetown</option>
                                    <option value="University of Florida">University of Florida</option>
                                    
                                    <option value="University of South Carolina">USC</option>
                                -->
                                    <option value="University of Texas">Texas (UT) - coming soon</option>
                                    <!--
                                    <option value="Dallas">Dallas</option>
                                    <option value="Los Angeles">Los Angeles</option>
                                    <option value="New York City">NYC</option>
    -->
                                    </select>
                                    
                                </div>
                            </div>
                        </div>
                        <div class="row cf">
                            <div class="lab l col-md-2">Dates</div>
                            <div class="inp r dates col-md-10">
                                <input type="text" placeholder="Check In" id="ci" value="" />
                                <input type="text" placeholder="Check Out" id="co" value="" />
                                <div class="select" style="height:32px;padding:5px 15px;">
                                    <select id="guests">
                                        <option selected="selected" value="1">1 Guest</option>
                                        <option value="2">2 Guests</option>
                                        <option value="3">3 Guests</option>
                                        <option value="4">4 Guests</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row type cf">
                            <div class="lab l col-md-2">Housing Type</div>
                            <div class="inp r col-md-10">
                                <div class="radio selectedx" data-id="pta">
                                    <span><i class="icon icon-thin-0959-city-flat-homes swagful"></i> Apartment</span>
                                </div>
                                <input type="checkbox" checked="checked" id="pta" style="display:none;" />
                                    <!--
                                <div class="radio">
                                    <input type="checkbox" checked="checked" id="twn" /><span>Townhouse</span></div>
                                -->
                                <div class="radio selectedx" data-id="pth">
                                   <span><i class="icon icon-thin-0046-home-house swagful"></i>House</span>
                                </div>
                                 <input type="checkbox" checked="checked" id="pth" style="display:none;" />
                                <!--
                                <div class="radio">
                                    <input type="checkbox" checked="checked" id="lft" /><span>Loft</span></div>
                                <div class="radio">
                                    <input type="checkbox" checked="checked" id="oth" /><span>Other</span></div>
                                <div class="radio">
                                    <input type="checkbox" checked="checked" id="flt" /><span>Flat</span></div>
                                
                                --><div class="radio selectedx" data-id="cdo">
                                
                                     <i class="icon icon-thin-0960-city-house-home swagful"></i> <span>Condo</span>
                                </div>
                                <input type="checkbox" checked="checked" id="cdo" style="display:none;" />
                                <!--<div class="radio">
                                    
                                    <input type="checkbox" checked="checked" id="dpx" /><span>Duplex</span></div>
                                -->
                            </div>
                        </div>
                        <div class="row type cf">
                            <div class="lab l col-md-2">Room Type</div>
                            <div class="inp r col-md-10">
                                <div class="radio selectedx" data-id="eth">
                                    <span><i class="icon icon-thin-0045-home-house swagful"></i>Entire Home</span>
                                </div>
                                  <input type="checkbox" checked="checked" id="eth" style="display:none;"/>

                                <div class="radio selectedx" data-id="prr">
                                    <span><i class="icon icon-thin-0576-door-exit-emergency-logout swagful"></i> Private Room</span>
                                </div>
                                <input type="checkbox" checked="checked" id="prr" style="display:none;"/>

                                <div class="radio selectedx" data-id="shr">
                                    <span><i class="icon icon-thin-0932-sofa-armchair swagful"></i> Shared Room</span>
                                </div>
                                <input type="checkbox" checked="checked" id="shr" style="display:none;"/>
                               
                            </div>
                        </div>
                        <div class="row range cf">
                            <div class="lab l col-md-2">Price Range</div>
                            <div class="inp r col-md-10">
                                <div class="drag">
                                    <div class="line" id="price-slider"></div>
                                    <div class="labs cf">
                                        <div class="lab1 labprice l" id="pricelo">0</div>
                                        <div class="lab3 labprice r" id="pricehi">4000</div>
                                        <div class="lab2">Per Week</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                    <div class="results">
                        <div class="title" id="result-cnt"></div>
                        <div class="cf" id="ct">

                        </div>
                    </div>
                
                
            </div>
            <div class="map col-md-5 col-sm-12 col-xs-12" id="map"></div>
                </div>
            <a href="/d/listing/1" class="tpl item l search-result hide">
                <div class="picture"></div><img class="person" />
                <div class="info"><span class="price"></span><span class="desc"></span></div>
            </a>
            <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
            <script>
                /*
                window.searchOpts = {
                    "guests": 1,
                    "area": "Florida State University"
                };
                */
            </script>
            <script src='/static/js/browse.js'></script>
        </div>

    </div>
  
{% endblock %}

{% block more_js_scripts %}
    <script>
    window.initial_filter = false;
    function do_first_filter(){
        if(!window.initial_filter){
            if('{{data.area}}' !== ''){
                $('#select').val('{{data.area}}'); 
            }
            if('{{data.ci}}' !== '' || '{{data.co}}' !== ''){
                var ci_co_obj = {
                    ci: '{{data.ci}}' || null,
                    co: '{{data.co}}' || null,
                }
                Template.events.dates.showGETDates(ci_co_obj);
            }

            if('{{data.guests}}' !== ''){
                $("#guests").val('{{data.guests}}');
            }
            window.initial_filter = true;
            return Map.moveMap(Map.redraw);
        }
    }
    do_first_filter();  
        
    </script>
{% endblock %}

africanawiki_geodata/templates/engine/dashboard.html
{% extends 'engine/engine_base.html' %}

{% block content %}
<div class="tab-content vbvb">
		    <div role="tabpanel" class="tab-pane active" id="home">
		    	<h2> Welcome to AfricanaWiki Data</h2>
		    	<p> If you're here seeing this, you are witnessing the birth of the first Pan-African Knowledge Database. Check out the latest dataset: </p>
		    	<p> <a href="/geo/minority_businesses" class="btn btn-success"> Visualized Geodata: United States Minority Businesses </a>
		    	</div>
		    <div role="tabpanel" class="tab-pane" id="requests">
		    	{% for r in requests %}
		    		<p><a href="{% url 'invitation_request_detail' pk=r.pk slug=r.slug %}">{{r}}</a></p>
		    	{% empty %}
		    		No invitation requests presently.
		    	{% endfor %}
		    </div>
		</div>
{% endblock %}

africanawiki_geodata/templates/engine/engine_anon_base.html
<html>
	<head>
		<title>
			AfricanaWiki Data
		</title>
		<script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
		<link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" />
		
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>	

		<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"></script>

		<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/4.10.1/bootstrap-social.min.css"></script>

		<link rel="stylesheet" type="text/css" href="/static/css/style.css" />
	</head>
	<body class="black">
        <nav style="max-height:2px;min-height:1px;overflow:auto;border-bottom:2px solid #0032A3;" role="banner">
                
            </nav>
		<div class="qw col-md-4 col-md-offset-4" style="margin-top:50px;">
			
			{% block content %}
			
		
			{% endblock %}
		</div>
	</body>
</html>

africanawiki_geodata/templates/engine/invitation_request_create.html
{% extends 'engine/engine_anon_base.html' %}

{% block content %}
<h2> Request an Invite to AfricanaWiki Data </h2>
<form action="." method="post" style="margin-bottom:30px;" enctype="multipart/form-data">
	{% csrf_token %}
{{form.as_p}}
<input type="submit" class="btn btn-success" value="Request An Invite" />
</form>
<script>
      $("input").each(function(i, item) {

                    if (!$(item).hasClass('form-control')) {
                        if (item.type !== 'checkbox') {
                            $(item).addClass('form-control nbr fcc');
                        }
                    }
                    if (item.value !== "") {
                        item.title = item.placeholder;
                        $(item).attr('data-toggle', 'tooltip');
                    }
                    
                });
      $('#id_email').attr('placeholder','Email Address (required)');
                    $('label[for="id_email"]').remove();

                    $('#id_full_name').attr('placeholder','Full Name (required)');
                    $('label[for="id_full_name"]').remove();

                    $('#id_desired_username').attr('placeholder','Desired Username (required)');
                    $('label[for="id_desired_username"]').remove();

                    $('#id_facebook_url').attr('placeholder','Facebook URL');
                    $('label[for="id_facebook_url"]').remove();

                    $('#id_twitter_url').attr('placeholder','Twitter URL');
                    $('label[for="id_twitter_url"]').remove();

                    $('#id_linkedin_url').attr('placeholder','LinkedIn URL');
                    $('label[for="id_linkedin_url"]').remove();

                    $('#id_github_url').attr('placeholder','Github URL');
                    $('label[for="id_github_url"]').remove();

                    $('#id_reddit_url').attr('placeholder','Reddit URL');
                    $('label[for="id_reddit_url"]').remove();

                    

                    $('#id_captcha_1').attr('placeholder',"Captcha Code (so we know you're not a robot)");

                    $('label[for="id_bio"]').remove();
                    $('textarea').attr('placeholder','Bio').css({'width':'100%'});
      </script>
{% endblock %}

africanawiki_geodata/templates/engine/invitation_request_detail.html
{% extends 'engine/engine_anon_base.html' %}

{% block content %}
{% if not request.user.is_authenticated %}
{% for m in messages %}
{{m}}

{% empty %}
{% endfor %}
{% endif %}
<h2> {{object}}'s Invitation Request </h2>
<p> Email: {{object.email}} </p>
<p> Full Name: {{object.full_name}} </p>
<p> Facebook URL: {{object.facebook_url}} </p>
<p> Twitter URL: {{object.twitter_url}} </p>
<p> Linkedin URL: {{object.linkedin_url}}</p>
<p> Github URL: {{object.github_url}} </p>
<p> Reddit URL: {{object.reddit_url}} </p>
<p> Timestamped Photo: <img src="/media/{{object.timestamped_photo}}" /></p>
<p> Bio: {{object.bio}} </p>

{% if request.user.is_authenticated %}
<a class="btn btn-success" href="/invite_user?email={{object.email}}"> Invite User </a>
{% endif %}
{% endblock %}

africanawiki_geodata/templates/engine/invite_user.html
{% extends 'engine/engine_base.html' %}

{% block more_css_in_head %}
	<style>
		input{
			color:#222
		}
	</style>
{% endblock %}
{% block left_sidebar %}
      <li class="cd-label">Main</li>
      <li class="overview" role="presentation" class="active">
        <a href="/dashboard" >Home</a>
      </li>
      <li class="cd-label">Datasets</li>
      <li class="overview">
        <a href="/geo/minority_businesses">Minority Businesses</a>
      </li>
      
      {% endblock %}
{% block content %}


      
<div class="vbvb">
	<h2> Invite a User to AfricanaWiki Data </h2>
	<form action="." method="post">
		{% csrf_token %}
		{{form.as_p}}

		<input type="submit" class="btn btn-success" value="Invite" />
	</form>
</div>

<script>
function get(name){
   if(name=(new RegExp('[?&]'+encodeURIComponent(name)+'=([^&]*)')).exec(location.search))
      return decodeURIComponent(name[1]);
}
if (get('email')){
	$('#id_email').val(get('email'));
}
</script>

{% endblock %}